### ISSUE TITLE
perform masking is a lower triangular matrix  in AR model, is it a bug?(在AR模型中后续数据的掩码遮盖矩阵正好是一个下三角矩阵，是否是代码的bug？)

### ISSUE THREAD

**Issue by liuhaozhe6788** [enhuiz/vall-e#61]
In vall_e/vall_e/base.py, for each transformer block of the AR model, the masking tensor should not be just a lower triangular matrix because text and prompts in tensor v can attend to each other. Therefore, the zero mask should be like a trapezoid rather than a triangle.
(在 vall_e/vall_e/base.py 中，掩码不应该只是一个下三角，因为张量v中的文本和语音提示可以相互关注，因此零掩码应该像梯形而不是三角形)

**Comment by huukim136** [comment]
I think when inference, the implementation is correct. It starts from the (text + prompt) sequence. That said, they can be all attended when predicting future tokens

**Comment by huukim136** [comment]
But when training, there are a few things I don't really get it yet:
- For prompt, I think it's fine because prompt is ignored when calculating the loss [here](https://github.com/enhuiz/vall-e/blob/3476d393d2133fa9b50d5ad999ca13b95fc22060/vall_e/vall_e/base.py#L453)
- For [text, it is not ignored](https://github.com/enhuiz/vall-e/blob/3476d393d2133fa9b50d5ad999ca13b95fc22060/vall_e/vall_e/base.py#L464) and taken to calculate NLL loss. I wonder should text and prompt be all ignored when training? Why we need to consider predicting to next text token when GT text is always given?  Is it a bug?

**Comment by cantabile-kwok** [comment]
> But when training, there are a few things I don't really get it yet:
> 
> * For prompt, I think it's fine because prompt is ignored when calculating the loss [here](https://github.com/enhuiz/vall-e/blob/3476d393d2133fa9b50d5ad999ca13b95fc22060/vall_e/vall_e/base.py#L453)
> * For [text, it is not ignored](https://github.com/enhuiz/vall-e/blob/3476d393d2133fa9b50d5ad999ca13b95fc22060/vall_e/vall_e/base.py#L464) and taken to calculate NLL loss. I wonder should text and prompt be all ignored when training? Why we need to consider predicting to next text token when GT text is always given?  Is it a bug?

@huukim136 I think you are right, it is strange indeed!

**Comment by fd873630** [comment]
@enhuiz 
I wonder why you used it like this. Can you explain? thank you :)
Maybe to reduce the average AR loss? If not, never mind.

**Comment by liuhaozhe6788** [comment]
> @enhuiz I wonder why you used it like this. Can you explain? thank you :) Maybe to reduce the average AR loss? If not, never mind.
I think the text should be ignored when calculating the loss function. Anyway, I modified the h_list and y_list when calculating loss [here](https://github.com/enhuiz/vall-e/blob/3476d393d2133fa9b50d5ad999ca13b95fc22060/vall_e/vall_e/base.py#L481) during training.
